services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
        env_file: "./backend/.env"
        command: sh -c "
            python weather_air_project/manage.py makemigrations &&
            python weather_air_project/manage.py migrate &&
            python weather_air_project/manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./backend:/backend

    frontend:
        build: ./frontend
        ports:
            - "5500:5500"
        volumes:
            - ./frontend:/frontend
        command: sh -c "
            python3 -m http.server 5500"
        depends_on:
            - backend